* About
The purpose of this package is to be able to play computer go games from a real go board.

Unlike the many other repositories which can read go board images, this one is /really dumb/. We assume the user has decent image quality and lighting and is taking the picture from directly in front of the board. We also require the user to input the corners of the board.

The upshot of that is that the code is easy to read and modify and the algorithm is very quick.

** Feature requests
Unfortunately I'm not in a place where I can take suggestions for features or review pull requests. I would highly encourage forking this code and modifying it to suit your needs as this suits mine!


* Developer instructions
We recommend using [[https://github.com/conda-forge/miniforge][miniforge]] for managing your python environments. You can create an environment for this package with

#+BEGIN_SRC 
  conda create -n goban_irl python=3.9
#+END_SRC

After you ~conda activate goban_irl~, you can install the package locally in editable mode with

#+BEGIN_SRC 
  python -m pip install -e .
#+END_SRC


